In [5]:
"""
Q1. Create the following arrays using NumPy:
• An array of 7 zeros.
• An array of 9 fives.
• An array from the list [2, 4, 6, 8, 10].
"""
import numpy as np

zeroarry = np.full(7, 0)
fullarry = np.full(9, 5)
listtoarry = np.array([2, 4, 6, 8, 10])
print(zeroarry, fullarry, listtoarry)

[0 0 0 0 0 0 0] [5 5 5 5 5 5 5 5 5] [ 2  4  6  8 10]


In [7]:
"""
Q2. Given the array arr = np.array([[1, 2, 3], [4, 5, 6]]), print:
• Its shape.
• Total number of elements (size).
• Number of dimensions (ndim).
• Extract all even numbers from the array.
"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)
print(arr.shape)
print(arr.ndim)

6
(2, 3)
2


In [13]:
"""
Q3. Given the array:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) 
• Print the element at the 3rd row, 2nd column.
• Slice the array to get the first and last rows.
"""
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[2, 1])
print(arr[[1, 2], :])

80
[[40 50 60]
 [70 80 90]]


In [15]:
"""
Q4. Given two arrays:
a = np.array([1, 3, 5]) 
b = np.array([2, 4, 6]) 
Compute:
• Element-wise addition (a + b).
• Element-wise multiplication (a * b).
"""
a = np.array([1, 3, 5]) 
b = np.array([2, 4, 6]) 
print(a+b)
print(a*b)


[ 3  7 11]
[ 2 12 30]


In [19]:
"""
Q5. For the array arr = np.array([1, 4, 9]), compute:
• Square root of each element.
• Natural logarithm of each element.
"""
arr = np.array([1, 4, 9])
print(np.sqrt(arr))
print(np.log(arr))

[1. 2. 3.]
[0.         1.38629436 2.19722458]


In [25]:
"""
Q6. Use NumPy to:
• Create an array of numbers from 5 to 50 with a step of 5.
• Create an array of 6 evenly spaced numbers between 0 and 1.
"""
range_arr = np.arange(5, 55, 5)
print(range_arr)
linarr = np.linspace(0, 1, 6)
print(linarr)

[ 5 10 15 20 25 30 35 40 45 50]
[0.  0.2 0.4 0.6 0.8 1. ]


In [27]:
"""
Q7. For the array data = np.array([12, 15, 18, 21, 24]), compute:
• Mean and median.
• Sum and cumulative sum.
"""
data = np.array([12, 15, 18, 21, 24])
print(np.mean(data))
print(np.median(data))
print(np.sum(data))
print(np.cumsum(data))

18.0
18.0
90
[12 27 45 66 90]


In [31]:
"""
Q8. Given a 2D array:
matrix = np.array([[1, 2], [3, 4], [5, 6]]) 
Write a program to:
• Subtract 2 from every element.
• Multiply each row by [0.5, 1.5]
"""
matrix = np.array([[1, 2], [3, 4], [5, 6]]) 

matrix_minus = matrix - 2
print(matrix_minus)

result = matrix* [0.5, 1.5]
print(result)


[[-1  0]
 [ 1  2]
 [ 3  4]]
[[0.5 3. ]
 [1.5 6. ]
 [2.5 9. ]]


In [ ]:
"""

"""

In [ ]:
"""

"""